<?php namespace JF;
/**

Copyright 2018 JQueryForm.com
License: http://www.jqueryform.com/license.php

FormID:  jqueryform-5fc7de
Date:    2018-01-14 11:39:24
Version: v2.1.0
Generated by http://www.jqueryform.com

PHP 5.3+ is required.
If mailgun is used AND the form has file upload field, PHP 5.5+ is required.

*/

class Config {
	private static $config;

    public static function getConfig( $decode = true ){
    	self::$config = self::_getConfig( $decode );
    	self::overwriteConfig();
    	return self::$config;
    }

    private static function _getConfig( $decode = true ){
        ob_start();
        // ---------------------------------------------------------------------
        // JSON format config
        // Note: please make a copy before you edit config manually
        // ---------------------------------------------------------------------

/**JSON_START**/ ?>
{
    "formId": "jqueryform-5fc7de",
    "email": {
        "to": "smnthsnyder@gmail.com",
        "cc": "",
        "bcc": "",
        "subject": "New Contact Request: {f37} {f42}",
        "template": "",
        "sendmail_from": "unforgettablefoodaffairs@gmail.com"
    },
    "admin": {
        "users": "admin:22c73",
        "dataDelivery": "emailAndFile"
    },
    "thankyou": {
        "url": "/thank-you.html",
        "message": "",
        "seconds": ""
    },
    "seo": {
        "trackerId": "",
        "title": "",
        "description": "",
        "keywords": "",
        "author": ""
    },
    "mailer": "smtp",
    "smtp": {
        "host": "smtp.gmail.com",
        "user": "unforgettablefoodaffairs@gmail.com",
        "password": "HannaBanana48!",
        "port": "465",
        "security": "ssl"
    },
    "mailgun": {
        "domain": "",
        "apiKey": "",
        "fromEmail": "",
        "fromName": ""
    },
    "styles": {
        "iCheck": {
            "enabled": true,
            "skin": "flat",
            "colorScheme": "black"
        },
        "Select2": {
            "enabled": true
        }
    },
    "logics": [

    ],
    "fields": [
        {
            "label": "Name",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small",
                "addon": {
                    "leftIcon": "glyphicon glyphicon-user"
                },
                "validators": {
                    "required": {
                        "enabled": true
                    }
                }
            },
            "cid": "c37",
            "id": "f37"
        },
        {
            "label": "Company",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small",
                "addon": {
                    "leftIcon": "fa fa-briefcase"
                }
            },
            "cid": "c42",
            "id": "f42"
        },
        {
            "label": "Email",
            "field_type": "email",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "sender": true,
                "validators": {
                    "email": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    }
                },
                "addon": {
                    "leftIcon": "glyphicon glyphicon-envelope"
                }
            },
            "cid": "c32",
            "id": "f32"
        },
        {
            "label": "Phone",
            "field_type": "phone",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "sender": false,
                "placeholder": "xxx-xxx-xxxx",
                "addon": {
                    "leftIcon": "glyphicon glyphicon-earphone"
                },
                "validators": {
                    "pattern": {
                        "enabled": true,
                        "val": "[0-9 -+.]+",
                        "msg": "Invalid phone number"
                    },
                    "required": {
                        "enabled": true
                    }
                },
                "hidden": false
            },
            "phone": {
                "validationMethod": "simple",
                "simpleFormat": "xxx-xxx-xxxx",
                "usePhoneLib": "N"
            },
            "cid": "c47",
            "labelHide": false,
            "id": "f47"
        },
        {
            "label": "Venue",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small",
                "addon": {
                    "leftIcon": "fa fa-building-o"
                }
            },
            "id": "f101",
            "cid": "c61"
        },
        {
            "label": "Event Date",
            "field_type": "date",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "addon": {
                    "rightIcon": "glyphicon glyphicon-th",
                    "rightText": "",
                    "leftIcon": "fa fa-calendar"
                },
                "date": {
                    "startDate": "0d"
                }
            },
            "id": "f102",
            "cid": "c67"
        },
        {
            "label": "Timeframe",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small",
                "addon": {
                    "leftIcon": "fa fa-clock-o"
                },
                "placeholder": "Ex: 3:00pm - 7:00pm"
            },
            "id": "f103",
            "cid": "c72"
        },
        {
            "label": "Estimated Guest Count",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small",
                "addon": {
                    "leftIcon": "fa fa-users"
                }
            },
            "id": "f104",
            "cid": "c79"
        },
        {
            "label": "Type of Menu Desired",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small",
                "addon": {
                    "leftIcon": "fa fa-cutlery"
                }
            },
            "id": "f105",
            "cid": "c84"
        },
        {
            "label": "How Did you Hear About Us?",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small",
                "addon": [

                ]
            },
            "cid": "c87",
            "id": "f87"
        },
        {
            "label": "Google reCaptcha",
            "field_type": "recaptcha",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                }
            },
            "labelHide": true,
            "recaptcha": {
                "theme": "light",
                "siteKey": "6LdJdgwUAAAAACXViZjG_r8pcrnw3BiFSjJlUyjF",
                "secretKey": "6LdJdgwUAAAAALAFf8pZZC3oCSCpFUaG6vx8-yni",
                "language": ""
            },
            "cid": "c25",
            "id": "f25"
        },
        {
            "label": "Submit Button",
            "field_type": "submit",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "slideshow": false
                },
                "page": {
                    "title": "Last Step",
                    "labelPrev": "< Back",
                    "isButtonPrev": false,
                    "showPageNumnber": false,
                    "pageNumberText": "{page} \/ {total}"
                }
            },
            "labelHide": true,
            "submit": {
                "label": "",
                "icon": "",
                "checkRequiredFields": ""
            },
            "cid": "c100",
            "id": "f100"
        }
    ]
}
<?php /**JSON_END**/

        $json = ob_get_clean() ;

        return $decode ? json_decode( trim($json), true ) : $json;
    } // end of getConfig()

    private static function getValue( $fieldId, $default = NULL ){
        return isset( $_POST[$fieldId] ) ? $_POST[$fieldId] : $default ;
    }

    private static function overwriteConfig(){
    	//self::get_to();
    }

    private static function get_to(){
    	$value = self::getValue( 'c25' );
    	$to = array(
    		'Option 1' => 'a@a.com',
    		'Option 2' => 'b@b.com',
    		'Option 3' => 'c@c.com',
    	);

    	if( isset( $to[$value] ) ){
    		self::$config['email']['to'] = $to[ $value ];
    	};
    }

} // end of Config class